project:
  type: website

website:
  title: "Mekhala Kumar"
  site-url: https://github.com/mekh09/about-me
  twitter-card:
    creator: "@UMassDACSS"
    site: "@UMassDACSS"
  favicon: images/DACSS_Round_Network.png
  navbar:
    background: "#881c1c"
    logo: images/UMass White Wordmark Horiz.png
    right:
      - text: "My work"
        href: https://mekh09.github.io/About-Mekhala-Kumar/
      - text: "About me"
        file: about.qmd
      - href: https://umass.edu/sbs/dacss
        text: "DACSS"
      - icon: github
        href: https://github.com/DACSS/DACSS_601_August2022_v2
        aria-label: GitHub

execution:
  freeze: auto


format:
  html:
    mainfont: Open Sans
    linkcolor: "#881c1c"
    toc: true
    theme: 
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
